### PR TITLE
Added hierarchy arguments to sbmtm.plot()

### PR DESCRIPTION
**Pull request by gaardhus**
Added the possibility to specify the size of the nodes and edges of the hierarchical graph through the sbmtm.plot() method.

### CODE REVIEW

**Comment by gaardhus** [comment]
Also added `.save_model()` and `.load_model()` methods to the sbmtm class.

**Comment by gaardhus** [comment]
Also added pickle `.save_model()` and `.load_model()` methods to the `sbmtm` class.

**Comment by gaardhus** [comment]
Also made some changes to sbmtm.print_summary();

- Added context managers for file and stdout
- Changed the argument from tofile[bool] to file[str] indicating the path of the file
- Changed default from writing to file to printing (as implied by the name of the method)

Please let me know if I should make separate pull requests for each of these updates, or if it's fine for me to pile them together.

**Comment by martingerlach** [comment]
Awesome. Looks good. The combined request works for me but not sure if others would object.
Sorry, for taking so long to review this pull-request. Thanks for contributing and improving this code : )

**Pull request merged**
