### PR TITLE
Fix deg_corr in fit()

### PR DESCRIPTION
**Pull request by fvalle1**
graph_tool has changed the way it handles deg_corr parameter for degree corrected ([bda49830](https://git.skewed.de/count0/graph-tool/-/commit/bda49830b4daa16388829b976b448d8c99e2f007)) this should be fixed in sbmtm.

### CODE REVIEW

**Comment by fvalle1** [comment]
I suggest to modify this also in master

**Review by martingerlach — APPROVED** [review]

**Comment by martingerlach** [comment]
Thanks, looks good.

**Comment by fvalle1** [comment]
I noticed that with recent version of graph-tool besides the different signature of minimise_nested_block_model, the fitting on bipartite networks fails. May be due to **clabel** param, I opened a related issue ([#706](https://git.skewed.de/count0/graph-tool/-/issues/706)) on graph-tool's git.

**Comment by martingerlach** [comment]
Great catch. I hadnt tested with the changes. 
From what I understand, the new changes will break fitting the bipartite network, correct?
Should we thus wait for the fix before merging the changes?

**Comment by fvalle1** [comment]
The issue [#706](https://git.skewed.de/count0/graph-tool/-/issues/706) with bipartite networks was just fixed by Tiago ([7be93ef457ac9b33563ddf498774d33326a94297](https://git.skewed.de/count0/graph-tool/-/commit/7be93ef457ac9b33563ddf498774d33326a94297)).

We must be sure users have the latest graph-tool to make these changes working.

Maybe it would be a good idea to have to branches one that works with graph-tool<2.40 and one compatible with newer versions of graph-tool.

**Comment by martingerlach** [comment]
I think we can merge this to the develop-branch and assume that you need the latest version of graph-tool. Lets wait before merging this into the main branch.
thanks for the update

**Pull request merged**
